# -*- coding: utf-8 -*-
"""mvmc_spin_jastrow.ipynb

Automatically generated by Colaboratory.
"""

# Commented out IPython magic to ensure Python compatibility.
!wget https://github.com/issp-center-dev/mVMC/releases/download/v1.1.1/mVMC-1.1.1.tar.gz
!tar xzvf mVMC-1.1.1.tar.gz
!mv mVMC mVMC-1.1.1
### apply the patch
# %cd mVMC-1.1.1/src/mVMC
!wget https://raw.githubusercontent.com/ryuikaneko/mvmc_spin_jastrow/master/mVMC-1.1.1__spin_jastrow_only__sz_nonfixed_only/src/mVMC/projection.patch
!patch -u projection.c < projection.patch
# %cd ../../../
### end of apply the patch
!mkdir -p mVMC-1.1.1.build
# %cd mVMC-1.1.1.build/
### fix bug in mVMC-1.1.1
!sed -i 's/shared(eleCfg, eleProjCnt, eleIdx, eleNum, ip)/shared(eleCfg, eleProjCnt, eleIdx, eleNum)/g' ../mVMC-1.1.1/src/mVMC/include/../calham.c
!sed -i 's/shared(eleCfg, eleProjCnt, eleIdx, eleNum, ip)/shared(eleCfg, eleProjCnt, eleIdx, eleNum)/g' ../mVMC-1.1.1/src/mVMC/include/../calham_real.c
### end of fix bug in mVMC-1.1.1
!cmake ../mVMC-1.1.1/
!make
